name: CI

on:
  push:
    branches:
      - main
      - feat/**
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1-mesa-dev

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          python -m pip install conan

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Install dependencies
        run: conan install . -of build -s build_type=Debug --build=missing

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake \
            -DCMAKE_PREFIX_PATH="$PWD/build"

      - name: Build
        run: cmake --build build -j

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
